CREATE DATABASE EMPRESA
USE EMPRESA
GO

CREATE TABLE PRODUCTOS(
ID_PRODUCTOS INT PRIMARY KEY IDENTITY (1,1),
CODIGO_PRODUCTO NVARCHAR (20) NOT NULL,
NOMBRE_PRODUCTO NVARCHAR (50) NOT NULL,
EXISTENCIA INT NOT NULL,
ESTADO BIT DEFAULT 1,
NOMBRE_PROVEEDOR NVARCHAR (30)

)

GO

CREATE TABLE USUARIOS(
ID_USUARIOS INT PRIMARY KEY IDENTITY (1,1),
NOMBRE_DE_USUARIO NVARCHAR (50) NOT NULL,
CONTRASEÑA NVARCHAR (16) NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
APELLIDO NVARCHAR (50) NOT NULL,	
CORREO NVARCHAR (50) NOT NULL,
TELEFONO NVARCHAR (9) NOT NULL,
ESTADO BIT DEFAULT 1,
FECHA_REGISTRO DATETIME DEFAULT GETDATE()

)

GO

CREATE TABLE OPCIONES (
ID_OPCIONES INT PRIMARY KEY IDENTITY (1,1),
NOMBRE_OPCION NVARCHAR (50),
ID_PRODUCTO_OPCION INT FOREIGN KEY REFERENCES PRODUCTOS(ID_PRODUCTOS),
ESTADO BIT DEFAULT 1


)

go